<?php
function menu_export_menu() {
    $items = array();
    $items['menu_export'] = array(
        'page callback' => 'say_hello_world',
        'access arguments' => array('access content'),
	    'delivery callback' => 'drupal_json_output'
     );
    return $items;
}


function say_hello_world() {
    $menu_main = menu_build_tree('main-menu');
    $menu_footer = menu_build_tree('menu-footer-menu');
    $output = Array();
    foreach ($menu_main as $menu_item) {
        $alias = drupal_lookup_path('alias', $menu_item['link']['link_path']);
        $url = $alias ? $alias : $menu_item['link']['link_path'];
    	$output['main'][] = Array('title' => $menu_item['link']['title'], 'link' => $url);
	}
    foreach ($menu_footer as $menu_item) {
        $alias = drupal_lookup_path('alias', $menu_item['link']['link_path']);
        $url = $alias ? $alias : $menu_item['link']['link_path'];
        $output['footer'][] = Array('title' => $menu_item['link']['title'], 'link' => $url);
    }
    return drupal_json_output($output);
}
